# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('media_content', models.FileField(blank=True, null=True, upload_to='content/')),
            ],
        ),
    ]
