# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_page', '0002_auto_20160906_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='media_content',
        ),
    ]
